### ISSUE TITLE
'502 Bad Gateway' error in openGWAS API page

### ISSUE THREAD

**Issue by BroQuan** [MRCIEU/opengwas#32]
When I click the url of openGWAS API: http://gwas-api.mrcieu.ac.uk/docs/, the error '502 Bad Gateway' occurred.

And the links in readme: 
https://ieugit-scmv-d0.epi.bris.ac.uk/ml18692/opengwas-api-internal
https://ieugit-scmv-d0.epi.bris.ac.uk/cmtsa/ieu-gwas-database
have expired.

Could someone help me? 
Thanks a lot!!! :)

**Comment by zhouyyyyanling** [comment]
When I click the url of openGWAS API: http://gwas-api.mrcieu.ac.uk/docs/, the error '502 Bad Gateway' occurred.

And the links in readme:
https://ieugit-scmv-d0.epi.bris.ac.uk/ml18692/opengwas-api-internal
https://ieugit-scmv-d0.epi.bris.ac.uk/cmtsa/ieu-gwas-database
have expired.

Could someone help me?
Thanks a lot!!! :)
